config/routes.rb
Rails.application.routes.draw do
  resources :registers

  resources :contacts

  get 'home/index'
  get 'home/aboutus'
  get 'home/events'
  get 'home/gallery'
  get 'home/sponsors'
  get 'home/contactus'
  get 'home/team'

  
  get '/gallery' =>'home#gallery'
  get '/aboutus' =>'home#aboutus'
  get '/events' =>'home#events'
 get '/sponsors' =>'home#sponsors'
  get '/team' =>'home#team'
  get '/contactus' =>'home#contactus'

   root 'home#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/register.rb
class Register < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    redirect_to root_path
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    redirect_to root_path
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
    redirect_to root_path
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      UserMailer.message_email(@contact).deliver
      if @contact.save
        format.html { redirect_to @contact, notice: 'Message submitted successfully.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :message)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	  @register = Register.new
  end
  def team
  	
  end
  def events
  	
  end
  def gallery
  	
  end
  def aboutus
  	
  end
  def sponsors
  	
  end
  def contactus
  @contact = Contact.new
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all
    ##redirect_to root_path
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
    redirect_to root_path
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
    redirect_to root_path
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
              
      if @register.save
        UserMailer.welcome_email(@register).deliver
        UserMailer.admin_email(@register).deliver
        format.html { redirect_to '/', notice: 'Your Registration is Successfull' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:name, :email, :register_no, :college_name, :dept_name, :mob_no)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/_new.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
	      <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <br><br>
    <div class="row">
    <div class="col-md-12">
    <h4 align="center" style="color:#fff;"><i class="fa fa-map-marker"></i> ADDRESS</h4>
    <br>
    <p align="center" style="color:#000;">A.R.Parthasarathi</p><br>
    <p align="center" style="color:#000;">Department of Mathematics Anna University, Chennai – 25.</p>
    <br>
    <p align="center" style="color:#fff;"><strong style="color:#000;">Phone </strong> : 9600173400   </p><br>
    <p align="center" style="color:#fff;"><strong style="color:#000;">Email-id</strong> : mathrix15@gmail.com   </p>
    </div>
    
    </div>
    <hr>
    <br><br>
        <h4 align="center" style="color:#fff; font-size:15px;"></i> CONTACT US</h4>
    <div class="row">
      <div class="col-xs-6">
        <div class="form-group">
          <input type="text" name="contact[name]"class="form-control" required="required" placeholder="Name">
        </div>
      </div>
      
      <div class="col-xs-6">
        <div class="form-group">
          <input type="email" name="contact[email]"class="form-control" required="required" placeholder="Email address">
        </div>
      </div>

    </div>
    <div class="row">
          <div class="col-xs-12">
            <div class="form-group">
              <textarea name="contact[message]" id="message" required="required" class="form-control" rows="8" placeholder="Message"></textarea>
            </div>
            <br>
          <div class="form-group">
          <button type="submit" class="btn btn-danger btn-lg">Send Message</button>
          </div>
          </div>
    </div>

<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Listing contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/aboutus.html.erb
<html>
<head>
<title>MathRix</title>
<link href="/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="/css/jquery.countdown.css" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
<script src="/js/hover_pack.js"></script>
	<script src="/js/jquery.chocolat.js"></script>
		<link rel="stylesheet" href="/css/chocolat.css" type="text/css" media="all" />
		<!--light-box-files -->
		<script type="text/javascript" charset="utf-8">
			$(function() {
				$('#example1 a').Chocolat();
			});
		</script>
	<script type="text/javascript" src="/js/jquery-hover-effect.js"></script>
	<script type="text/javascript">
	//Image Hover
	jQuery(document).ready(function(){
	jQuery(function() {
		jQuery('ul.da-thumbs > li').hoverdir();
	});
	});
	</script>
</head>
<body>
	<!-- header-section-starts -->
	<div class="header">
        <div class="container">
        <div class="w-col w-col-1 logo">   
            <div class="logo">
                <a href="/"><img src="/images/logo/logo_dark.png" width="80" height="80" alt="" /></a> 
            </div>
            </div>
            <div class="w-col w-col-2 logo">
            <br><br>
            <h3 style=" margin-left:15px; color: #fff;font-size:30px;">MathRix</h3>
            </div>
            <div class="top-menu">
			<span class="menu"> </span>
                <ul class="cl-effect-1">
                <br>
                   <li><a  href="/">Home</a></li>
                    <li><a class="active" href="/aboutus">About</a></li>
                    <li><a href="/events">Events</a></li>
                    <li><a href="/gallery">Gallery</a></li>
                    <li><a href="/sponsors">Sponsors</a></li>
                    <li><a  href="/team">Team</a></li>
                    <li><a href="/contactus">Contact</a></li>
                </ul>
            </div>
			<!-- script-for-menu -->
		<script>
			$("span.menu").click(function(){
				$(".top-menu ul").slideToggle("slow" , function(){
				});
			});
		</script>
		<!-- script-for-menu -->
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- header-section-ends -->
    <!-- about-section -->
    
	<div class="about text-center">
	<div class="container">
	<div class="row-fluid PageHead">
	
	<div class="span12">
	<span> <img src="/images/logo/anna_logo.png" width="150" height="150" alt="______"></span>
	<h3>ANNA UNIVERSITY</h3>
	</div>
	
	
	
	<p class="lead text-center" align="center">The College of Engineering , Guindy in chennai ,India is  India's oldest Engineering and technical institution established in 1794. Having committed itself to provide excellent engineering education with an Indian traditional skills, professional ethics and moral standards of the student community, today it has risen to the extent of being one of the four constituent colleges of Anna University and one of the most prestigious and highly selective engineering institutions in the country. It is no wonder that every student of CEG takes pride of being called CEGian.</p>
	
	<a target="_blank" style="color:#207584;" class="btn btn-link" href="https://www.annauniv.edu/">More ..</a>

	<div class="row-fluid theteam">
	<div class="span2"></div>
	<div class="span2"></div>
	<div class="span2"><img src="/images/aboutus/act.jpg" height="120" alt="team"></div>
	<div class="span2"><img src="/images/aboutus/annauniv.jpg" height="120" alt="team"></div>
	<div class="span2"></div>
	<div class="span2"></div>
	<div class="clearfix"></div>
	</div>
	</div>
	<br>
	<br>
	<div class="container">
	<div class="row-fluid PageHead inverse">
	<div class="span12">
	<span> <img style="background-color:#fff;" src="/images/logo/mcs.png"  alt="______"></span>
	<br><br>
	<h3>MATHEMATICS COLLOQUIUM</h3>
	</div>
	<p class="lead text-center">


	The Department of Mathematics which is one of the largest units of Anna University caters to the needs of the Under-Graduate and Post-Graduate programmes in Science, Engineering and Technology. The Department of Mathematics provides high quality teaching with its never ending vision to achieve excellence. The Mathematics Colloquium has been conducting an intercollegiate students’ meet “MATHRIX” every year for the past two decades in order to instill the significance of mathematics in this age of information and technology. Mathrix has always been one of the fascinating and vibrant tech cum math fest for students from various colleges. Events that bring out talents, test capabilities of students and challenge mathematical, technical and analytical skills are conducted as part of the extravaganza. Every year Mathrix receives overwhelming support, guidance and suggestions from various patrons and students. We are sure that Mathrix’15 will be a grand success.</p>
		<a target="_blank" style="color:#207584;" class="btn btn-link" href="http://www.mcsau.in/">More ..</a>

	<div class="row-fluid theteam">
	<div class="span2"></div>
	<div class="span2"><img src="/images/aboutus/main.jpg" height="120" alt="team"></div>
	<div class="span2"><img src="/images/gallery/img1.jpg" height="120" alt="team"></div>
	<div class="span2"><img src="/images/aboutus/mathrix11.jpg" height="120" alt="team"></div>
	<div class="span2"><img src="/images/aboutus/mathrix14.jpg" height="120" alt="team"></div>
	<div class="span2"></div>
	<div class="clearfix"></div>
	</div>
	<br><br>
	</div>
	</div>
	
	</div>
	</div>
	<a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button"  data-toggle="tooltip" data-placement="left"><img src="/images/up.png" width="20" height="20"></a>

	</body>
</html>

app/views/home/contactus.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>MathRix</title>
<link href="/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/js/jquery.min.js"></script>
<!-- Latest compiled and minified CSS -->

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<!-- Custom Theme files -->
<link href="/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="/css/jquery.countdown.css" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="SONGLILY Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
<script src="/js/hover_pack.js"></script>
	<script src="/js/jquery.chocolat.js"></script>
		<link rel="stylesheet" href="/css/chocolat.css" type="text/css" media="all" />
		<!--light-box-files -->
		<script type="text/javascript" charset="utf-8">
			$(function() {
				$('#example1 a').Chocolat();
			});
		</script>
		<script type="text/javascript" src="/js/jquery-hover-effect.js"></script>
		<script type="text/javascript">
	//Image Hover
	jQuery(document).ready(function(){
	jQuery(function() {
		jQuery('ul.da-thumbs > li').hoverdir();
	});
	});
	</script>
</head>
<body>
	<!-- header-section-starts -->
	<div class="header">
        <div class="container">
            <div class="w-col w-col-1 logo">      
            <div class="logo">
                <a href="/"><img src="/images/logo/logo_dark.png" width="80" height="80" alt="" /></a> 
            </div>
            </div>
            <div class="w-col w-col-2 logo">
            <br><br>
            <h3 style=" margin-left:15px; color: #fff; font-size:30px;">MathRix</h3>
            </div>
            <div class="top-menu">
			<span class="menu"> </span>
                <ul class="cl-effect-1">
                <br>
                    <li><a  href="/">Home</a></li>
                    <li><a href="/home/aboutus">About</a></li>
                    <li><a  href="/home/events">Events</a></li>
                    <li><a  href="/home/gallery">Gallery</a></li>
                    <li><a href="/home/sponsors">Sponsors</a></li>
                    <li><a  href="/home/team">Team</a></li>
                    <li><a class="active" href="/home/contactus">Contact</a></li>
                </ul>
            </div>
			<!-- script-for-menu -->
			<script>
			$("span.menu").click(function(){
				$(".top-menu ul").slideToggle("slow" , function(){
				});
			});
			</script>
			<!-- script-for-menu -->
            <div class="clearfix"></div>
        </div>
    </div>
    <!-- header-section-ends -->
	<!-- contact -->
	<div class="contact-main">
			<div class="contact">
				<div class="container">
					<div class="contact-section">
					<h3>Contact </h3>
					 <div class="row">
						<%= render '/contacts/new'%>
					</div>
					

			 	 </div>
			   </div>
			   

	

			</div>
			
	<div class="social-network">
        <div class="social-network1">
				<a target="_blank" href="https://www.facebook.com/pages/MathRix/183380621687043?ref=aymt_homepage_panel">
				<i class="facebook"></i>
                <p>like Us On Facebook</p>
				<div class="clearfix"></div>
				</a>
        </div>
        <div class="social-network2">
			<a target="_blank" href="#">
			<i class="twitter"></i>
			<p>Follow us On Twitter</p>
			</a>
        </div>
        <div class="social-network3">
			<a target="_blank" href="#">
			<i class="googlepluse"></i>
			<p>Follow Us On Google+</p>
			</a>
        </div>
        <div class="clearfix"></div>
    </div>
    <div class="map">
        <iframe width="600" height="400" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.co.in/maps?hl=en&amp;safe=off&amp;q=Anna+University,+Chennai,+Tamil+Nadu+Arts+%26+Crafts+Store,+College+Bookstore&amp;ie=UTF8&amp;hq=Arts+%26+Crafts+Store,+College+Bookstore&amp;hnear=Anna+University+Parking,+Chennai,+Tamil+Nadu&amp;t=h&amp;iwloc=lyrftr:h,13984805977349966441,13.011347,80.23552&amp;ll=13.011632,80.235783&amp;spn=0.001419,0.002642&amp;output=embed"></iframe>
    </div>
    <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button"  data-toggle="tooltip" data-placement="left"><img src="/images/up.png" width="20" height="20"></a>

		</div>
   <!-- contact -->
    <!-- footer-section-starts -->
	<div class="footer">
		<div class="copy-rights text-center">
		</div>			
	</div>
	<!-- footer-section-ends -->
</body>
</html>

app/views/home/sponsors.html.erb
<html>
<head>
<title>MathRix</title>
<link href="/css/bootstrap.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="/js/jquery.min.js"></script>
<!-- Custom Theme files -->
<link href="/css/style.css" rel="stylesheet" type="text/css" media="all" />
<link rel="stylesheet" href="/css/jquery.countdown.css" />
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="SONGLILY Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!--webfont-->
<link href='http://fonts.googleapis.com/css?family=Oxygen:400,300,700' rel='stylesheet' type='text/css'>
<script src="/js/hover_pack.js"></script>
<script src="/js/jquery.chocolat.js"></script>
<link rel="stylesheet" href="/css/chocolat.css" type="text/css" media="all" />
<!--light-box-files -->
<script type="text/javascript" charset="utf-8">
$(function() {
    $('#example1 a').Chocolat();
    });
</script>
<script type="text/javascript" src="/js/jquery-hover-effect.js"></script>
<script type="text/javascript">
//Image Hover
jQuery(document).ready(function(){
    jQuery(function() {
      jQuery('ul.da-thumbs > li').hoverdir();
      });
    });
</script>
<script src="/js/easyResponsiveTabs.js" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function () {
    $('#horizontalTab').easyResponsiveTabs({
type: 'default', //Types: default, vertical, accordion           
width: 'auto', //auto or any width like 600px
fit: true   // 100% fit in a container
});
    });
</script>
</head>
<body>
<!-- header-section-starts -->
<div class="header">
  <div class="container">
    <div class="w-col w-col-1 logo">   
      <div class="logo">
        <a href="/"><img src="/images/logo/logo_dark.png" width="80" height="80" alt="" /></a>
      </div>
    </div>
    <div class="w-col w-col-2 logo">
      <br><br>
      <h3 style=" margin-left:15px; color: #fff; font-size:30px;">MathRix</h3>
    </div>
    <div class="top-menu">
      <span class="menu"> </span>
      <ul class="cl-effect-1">
        <br>
        <li><a  href="/">Home</a></li>
        <li><a href="/aboutus">About</a></li>
        <li><a  href="/events">Events</a></li>
        <li><a  href="/gallery">Gallery</a></li>
        <li><a class="active" href="/sponsors">Sponsors</a></li>
        <li><a  href="/team">Team</a></li>
        <li><a href="/contactus">Contact</a></li>
      </ul>
    </div>
    <!-- script-for-menu -->
    <script>
$("span.menu").click(function(){
    $(".top-menu ul").slideToggle("slow" , function(){
      });
    });
    </script>
    <!-- script-for-menu -->
    <div class="clearfix"></div>
  </div>
</div>
<!-- header-section-ends -->
<!-- single-section -->
<div class="main">
  <div class="container">
    <h3 align ="center" style="color: #fff; font-size:40px;">SPONSORS</h3> 
    <br><br>
    <div class="section group">
      

      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/cat.jpg" alt="">
      </div>

      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/cs.png" alt="">
      </div>
      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/fathima.jpg" alt="">
      </div>
      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/iob.jpg" alt="">
      </div>
      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/logo.jpg" alt="">
      </div>
      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/tanscst.jpg" alt="">
      </div>
      <div class="gallery-box">
        <div id="nivo-lightbox-demo"> <p>  </p></div>     
        <img src="/images/logo/sponsor logos/fresh.jpg" alt="Freshdesk">
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
  <a id="back-to-top" href="#" class="btn btn-primary btn-lg back-to-top" role="button"  data-toggle="tooltip" data-placement="left"><img src="/images/up.png" width="20" height="20"></a>

</div>
<!-- footer-section-starts -->
<div class="footer">
  <div class="copy-rights text-center">
  </div>			
</div>
<!-- footer-section-ends -->
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MathRix'15</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="shortcut icon" href="/images/fav.ico">
  <!-- Latest compiled and minified CSS -->
  <!-- Latest compiled and minified CSS 
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">-->
<!-- Optional theme -->

<!-- Latest compiled and minified JavaScript -->
</head>
<body>

		
<%= yield %>

</body>
</html>

app/views/registers/edit.html.erb
<h1>Editing register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<h1>Listing registers</h1>

<table>
  <thead>
    <tr >
      <th >Name</th>
      <th>Email</th>
      
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= register.name %></td>
        <td><%= register.email %></td>
       
         </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/registers/new.html.erb
<h1>New register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path %>

app/views/registers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @register.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @register.email %>
</p>

<p>
  <strong>Register no:</strong>
  <%= @register.register_no %>
</p>

<p>
  <strong>College name:</strong>
  <%= @register.college_name %>
</p>

<p>
  <strong>Dept name:</strong>
  <%= @register.dept_name %>
</p>

<p>
  <strong>Mob no:</strong>
  <%= @register.mob_no %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>